### ISSUE TITLE
Upgrade globby to latest version

### ISSUE THREAD

**Issue by altro3** [sindresorhus/cpy#84]
Now I have warnings in console log:
```
warning cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
These warnings already fixed in all libraries. All what you need - upgarde globby to version **11.0.3**

**Comment by sindresorhus** [comment]
Pull request welcome, but it will require some changes for Windows.

**Comment by Flavyoo** [comment]
I had a PR up for this, but closed it since there was a duplicate one. What kind of changes do you think are needed? I can try and help.

**Comment by TheWyo** [comment]
I did some digging into this to see what's up on Windows, here's what I found:

- globby 11 isn't returning anything on Windows when using backslashes per a change in v10. (https://github.com/sindresorhus/globby/issues/155#issuecomment-732961466)
- This due to a change in fast-glob, which in turn uses micromatch which keeps backslashes for escaping, even on Windows (per README https://github.com/micromatch/micromatch#backslashes).
- Unit test failure is then due to globby returning an empty array when trying to get the source file for the 2 affected unit tests.

cpy *could* be updated to do `.replace(/\\/g, '/')` on windows, but micromatch recommends against this (and it doesn't seem like a great solution, there's bound to be cases where blindly applying that to users' patterns would be wrong). So instead seems like the only option might be to have cpy have the same "only use forward slashes" requirement as globby.

If that approach is taken, all that's needed to get the 2 affected tests passing again is to do two things:
1. Run `.replace(/\\/g, '/')` on `t.context.tmp` (replacement here should be safer as we're actually expecting to receive a path here, not potentially a pattern that could have escapes), and use that in place of the current direct usages of `t.context.tmp`.
2. To avoid node's path lib inserting backslashes, swap `path.join` calls to `path.posix.join`.

These might be things worth considering applying to all the tests for consistency rather than making an exception of those 2.

Happy to make a PR if people are happy with this approach.
